WebAppCore/Pages/Timesheet/Admin/Index.cshtml.cs
using BusinessServices.Contracts;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models.BO;
using Models.BO.ViewModels;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCore.Pages.Timesheet.Admin
{
    [Authorize(Roles = "Admin")]
    public class IndexModel : PageModel
    {
        private readonly IServiceFactory serviceFactory;
        private readonly UserManager<User> userManager;
        private readonly IHttpContextAccessor accessor;

        public IList<TimesheetVm> TimesheetVm { get; set; }
        public IList<User> Users { get; set; }
        public IList<TotalHoursConsultantWiseVm> TotalHoursConsultantWiseVms { get; set; }
        public string Rpt { get; set; } = "C:\\Temp\\Consultant.pdf";


        [BindProperty]
        public bool isSubmitted { get; set; }

        [BindProperty]
        public bool DisableEntries { get; set; }

        [BindProperty]
        public WeeksOfYearVm WeeksOfYearVm { get; set; }

        [BindProperty]
        public string CurrentWeekNumber { get; set; }


        public IndexModel(IServiceFactory serviceFactory, UserManager<User> userManager,
            IHttpContextAccessor accessor)
        {
            this.serviceFactory = serviceFactory;
            this.userManager = userManager;
            this.accessor = accessor;
        }

        public async Task<IActionResult> OnGet()
        {
            DisableEntries = false;
            TimesheetVm = new List<TimesheetVm>();
            WeeksOfYearVm = this.serviceFactory.WeeksOfYearService.GetWeekByDate(DateTime.Now.Date);

            TotalHoursConsultantWiseVms = this.serviceFactory.SPTotalHoursConsultantWiseService
                                                .GetTotalHoursConsultantWise(WeeksOfYearVm.StartDate, WeeksOfYearVm.EndDate).ToList();
            TempData["CurrentWeekNumber"] = WeeksOfYearVm.WeekNumber;
            await GetTimesheetForUI();
            return Page();
        }

        public async Task<IActionResult> OnPostMain(List<TimesheetVm> timesheetVm, string hdnTotalWorkHours, string hdnTotalLunchHours)
        {
            var tempTimesheetVm = new List<TimesheetVm>();
            tempTimesheetVm = timesheetVm;
            var user = await userManager.FindByNameAsync(User.Identity.Name);

            if (user == null)
            {
                return RedirectToPage("./NotFound");
            }

            foreach (var entry in tempTimesheetVm)
            {
                entry.isSubmitted = isSubmitted;
                entry.SubmittedBy = user.Id;
                entry.SubmittedDate = DateTime.Now;
                entry.SubmittedFrom = accessor.HttpContext.Connection.RemoteIpAddress.ToString();
            }

            this.serviceFactory.TimesheetEntryService.CreateRange(tempTimesheetVm);

            return RedirectToPage("./Success");
        }


        public void OnPostEdit(string weekId, string weekId1)
        {
            CurrentWeekNumber = TempData["CurrentWeekNumber"].ToString();
            TempData["CurrentWeekNumber"] = CurrentWeekNumber;

            //TimesheetVm = new List<TimesheetVm>();
            //WeeksOfYearVm = new WeeksOfYearVm();
            WeeksOfYearVm = this.serviceFactory.WeeksOfYearService.GetWeekByWeekNumber(Convert.ToInt32(weekId));


            if (weekId1 == "dec")
            {
                WeeksOfYearVm.WeekNumber -= 1;
                WeeksOfYearVm = this.serviceFactory.WeeksOfYearService.GetWeekByWeekNumber(Convert.ToInt32(WeeksOfYearVm.WeekNumber));

                TotalHoursConsultantWiseVms = this.serviceFactory.SPTotalHoursConsultantWiseService
                                           .GetTotalHoursConsultantWise(WeeksOfYearVm.StartDate, WeeksOfYearVm.EndDate).ToList();

                //await GetTimesheetForUI();
            }
            else if (weekId1 == "inc")
            {
                WeeksOfYearVm.WeekNumber += 1;
                WeeksOfYearVm = this.serviceFactory.WeeksOfYearService.GetWeekByWeekNumber(Convert.ToInt32(WeeksOfYearVm.WeekNumber));

                TotalHoursConsultantWiseVms = this.serviceFactory.SPTotalHoursConsultantWiseService
                                           .GetTotalHoursConsultantWise(WeeksOfYearVm.StartDate, WeeksOfYearVm.EndDate).ToList();

                //await GetTimesheetForUI();
            }
            else
            {

            }
        }

        private async Task GetTimesheetForUI()
        {
            WeeksOfYearVm = this.serviceFactory.WeeksOfYearService.GetWeekByWeekNumber(WeeksOfYearVm.WeekNumber);
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            TimesheetVm = this.serviceFactory.TimesheetEntryService.GetUnApprovedTimesheetForWeek(WeeksOfYearVm.StartDate, WeeksOfYearVm.EndDate, user.Id).ToList();
            if (TimesheetVm.Count > 0)
            {
                if (TimesheetVm.Any(ts => ts.isSubmitted))
                {
                    DisableEntries = true;
                }
            }
            else
            {
                if (WeeksOfYearVm.WeekNumber.ToString() == CurrentWeekNumber)
                {
                    CreateTimesheetUI();
                }

            }
        }

        private void CreateTimesheetUI()
        {
            var days = (WeeksOfYearVm.EndDate - WeeksOfYearVm.StartDate).TotalDays + 1;

            for (int i = 0; i < days; i++)
            {
                var currDate = WeeksOfYearVm.StartDate.AddDays(i);

                TimesheetVm.Add(new TimesheetVm
                {
                    Day = currDate.ToString("dddd"),
                    Date = currDate,
                    WorkHours = 0F,
                    LunchHours = 0F,
                    Comments = ""
                });
            }
        }


        public async Task<IActionResult> OnPostView(string weekId, string weekId1, string userId, string clientId)
        {
            var user = await userManager.FindByIdAsync(userId);
            WeeksOfYearVm = this.serviceFactory.WeeksOfYearService.GetWeekByWeekNumber(Convert.ToInt32(weekId));

            TimesheetVm = this.serviceFactory.TimesheetEntryService.GetUnApprovedTimesheetForWeek(WeeksOfYearVm.StartDate, WeeksOfYearVm.EndDate, user.Id).ToList();

            var users = this.userManager.Users.Where(u => u.Client == clientId).ToList();
            User ClientUser = null;

            for (var i = 0; i < users.Count; i++)
            {
                if (await userManager.IsInRoleAsync(users[i], "Client"))
                {
                    ClientUser = users[i];
                    break;
                }
            }

            var content = WriteBytes(TimesheetVm, user, ClientUser);

            //return new FileContentResult(content, "application/msword");

            return new FileContentResult(content, "application/pdf");
        }
        private byte[] GeneratePdf(IList<TimesheetVm> timesheetVm, User user, User ClientUser)
        {
            var client = this.serviceFactory.ClientService.GetById(Guid.Parse(user.Client));

            using (System.IO.MemoryStream memoryStream = new System.IO.MemoryStream())
            {
                Document document = new Document(PageSize.A4, 10, 10, 10, 10);

                PdfWriter writer = PdfWriter.GetInstance(document, memoryStream);
                document.Open();

                //var font = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.WINANSI, BaseFont.EMBEDDED);
                Font boldArial = FontFactory.GetFont("Arial", 12, Font.BOLD);
                //Font verdana = FontFactory.GetFont("Verdana", 16, Font.BOLDITALIC, new Color(125, 88, 15));

                PdfPTable tableHeader = new PdfPTable(1);
                PdfPCell titleCell = new PdfPCell(new Phrase("TIME SHEET", new Font { Size = 20 }));
                titleCell.Border = 0;
                titleCell.HorizontalAlignment = 1;
                tableHeader.AddCell(titleCell);

                document.Add(tableHeader);

                tableHeader.SpacingBefore = 20f;
                tableHeader.SpacingAfter = 15f;

                PdfPTable tableConsultantHeader = new PdfPTable(4);

                PdfPCell nameLabelCell = new PdfPCell(new Phrase("Consultant Name: ", boldArial));
                nameLabelCell.Border = 0;
                tableConsultantHeader.AddCell(nameLabelCell);
                PdfPCell nameCell = new PdfPCell(new Phrase(user.FirstName + " " + user.LastName));
                nameCell.Border = 0;
                tableConsultantHeader.AddCell(nameCell);


                PdfPCell clientLabelCell = new PdfPCell(new Phrase("Client: ", boldArial));
                clientLabelCell.Border = 0;
                tableConsultantHeader.AddCell(clientLabelCell);
                PdfPCell clientCell = new PdfPCell(new Phrase(client.Name));
                clientCell.Border = 0;
                tableConsultantHeader.AddCell(clientCell);

                PdfPCell periodLabelCell = new PdfPCell(new Phrase("Period Ending Date: ", boldArial));
                periodLabelCell.Border = 0;
                tableConsultantHeader.AddCell(periodLabelCell);
                var contractEndDate = user.ContractEndTime == null ? "" : user.ContractEndTime.Value.ToShortDateString();
                PdfPCell periodCell = new PdfPCell(new Phrase(contractEndDate));
                periodCell.Border = 0;
                tableConsultantHeader.AddCell(periodCell);

                PdfPCell supervisorLabelCell = new PdfPCell(new Phrase("Supervisor: ", boldArial));
                supervisorLabelCell.Border = 0;
                tableConsultantHeader.AddCell(supervisorLabelCell);

WebAppCore/Pages/Timesheet/Client/DSReturn.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppCore.Pages.Timesheet.Client
{
    public class DSReturnModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WebAppCore/Pages/Timesheet/Admin/Index.cshtml
@page

@model WebAppCore.Pages.Timesheet.Admin.IndexModel

@{
    ViewData["Title"] = "Weekly Hour Summary";
}

@*<h2>Weekly Hour Summary</h2>*@

<div style="margin-top:20px;" class="row">
    <div class="col-md-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Weekly Hour Summary</h3>
            </div>
            <div class="panel-body">
                <input type="hidden" id="hdnTotalWorkHours" name="hdnTotalWorkHours" />
                <input type="hidden" asp-for="@Model.WeeksOfYearVm" value="@Model.WeeksOfYearVm" />
                <div class="row">
                    <div class="col-md-12 text-center">
                        <input type="hidden" asp-for="@Model.WeeksOfYearVm.WeekNumber" />
                        <label asp-for="@Model.WeeksOfYearVm.WeekNumber">
                            Week: @Model.WeeksOfYearVm.WeekNumber
                        </label>
                    </div>
                </div>
                <div class="row">
                    <form asp-page-handler="edit" method="post">
                        <div class="col-md-2">
                            <button style="margin-left:100px;" type="submit" asp-page-handler="edit" class="btn btn-default" asp-route-weekId1="dec" asp-route-weekId=" @Model.WeeksOfYearVm.WeekNumber">
                                <i class="glyphicon glyphicon-circle-arrow-left"></i>
                            </button>
                        </div>
                        <div class="col-md-4">
                            <input disabled asp-for="@Model.WeeksOfYearVm.StartDate" type="date" class="form-control col-md-3" />
                        </div>
                        <div class="col-md-4">
                            <input disabled asp-for="@Model.WeeksOfYearVm.EndDate" type="date" class="form-control col-md-3" />
                        </div>
                        <div class="col-md-2">
                            <button type="submit" asp-page-handler="edit" class="btn btn-default" asp-route-weekId1="inc" asp-route-weekId=" @Model.WeeksOfYearVm.WeekNumber">
                                <i class="glyphicon glyphicon-circle-arrow-right"></i>
                            </button>
                        </div>
                    </form>
                </div>
                <form method="post" style="margin-top:20px;">
                    <div class="form-group">

                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        Consultant
                                    </th>
                                    <th>
                                        Client
                                    </th>
                                    <th>
                                        Project
                                    </th>
                                    <th>
                                        Total Hours
                                    </th>
                                    <th>
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    @if (Model.TotalHoursConsultantWiseVms != null && Model.TotalHoursConsultantWiseVms.Any())
                                    {
                                        @for (int i = 0; i < Model.TotalHoursConsultantWiseVms.Count; i++)
                                        {
                                            <tr>
                                                <td>
                                                    <input type="hidden" asp-for="@Model.TotalHoursConsultantWiseVms[i].FirstName" />
                                                    <label style="font-weight:lighter" asp-for="@Model.TotalHoursConsultantWiseVms[i].FirstName">
                                                        @Model.TotalHoursConsultantWiseVms[i].FirstName @Model.TotalHoursConsultantWiseVms[i].LastName
                                                    </label>
                                                </td>
                                                <td>
                                                    <input type="hidden" asp-for="@Model.TotalHoursConsultantWiseVms[i].ClientName" />
                                                    <label style="font-weight:lighter" asp-for="@Model.TotalHoursConsultantWiseVms[i].ClientName">
                                                        @Model.TotalHoursConsultantWiseVms[i].ClientName
                                                    </label>
                                                </td>
                                                <td>
                                                    <input type="hidden" asp-for="@Model.TotalHoursConsultantWiseVms[i].ProjectName" />
                                                    <label  style="font-weight:lighter"asp-for="@Model.TotalHoursConsultantWiseVms[i].ProjectName">
                                                        @Model.TotalHoursConsultantWiseVms[i].ProjectName
                                                    </label>
                                                </td>
                                                <td>
                                                    <input type="hidden" asp-for="@Model.TotalHoursConsultantWiseVms[i].TotalHours" />
                                                    <label style="font-weight:lighter" asp-for="@Model.TotalHoursConsultantWiseVms[i].TotalHours">
                                                        @Model.TotalHoursConsultantWiseVms[i].TotalHours
                                                    </label>

                                                </td>

                                                <td style="width:10%">
                                                    <div class="form-group">
                                                        <button formtarget="_blank" type="submit" asp-page-handler="view" class="btn btn-default" asp-route-clientId="@Model.TotalHoursConsultantWiseVms[i].ClientId" asp-route-userId="@Model.TotalHoursConsultantWiseVms[i].Id" asp-route-weekId1="inc" asp-route-weekId=" @Model.WeeksOfYearVm.WeekNumber">
                                                            <i class="glyphicon glyphicon-circle-arrow-down"></i>
                                                        </button>
                                                    </div>
                                                </td>



                                            </tr>
                                        }

                                    }
                                }
                            </tbody>
                        </table>

                    </div>
                    @*<div class="panel-footer">
                            <div class="form-check m-1">
                                <input asp-for="@Model.isSubmitted" class="form-check-input" />
                                <label class="form-check-label" asp-for="@Model.isSubmitted">
                                    Check to submit
                                </label>
                            </div>
                            <input type="submit" asp-page-handler="main" value="Submit" class="btn btn-default" />
                        </div>*@
                </form>
            </div>

        </div>
    </div>

</div>

WebAppCore/Pages/Timesheet/Admin/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h2>Your timesheet was not found</h2>
@*<a asp-page="./Index" class="btn btn-primary">See All Timesheet</a>*@